/** True for assets served from /public without going through the image optimizer. */
export function isLocalPublicAsset(src: string): boolean {
  return (
    src.startsWith("/media/") ||
    src.startsWith("/uploads/") ||
    src.startsWith("/brand/") ||
    src.startsWith("/api/media/")
  );
}

/** Vercel Blob and other remote CMS uploads. */
export function isRemoteCmsAsset(src: string): boolean {
  return (
    src.includes(".blob.vercel-storage.com/") ||
    src.includes(".public.blob.vercel-storage.com/")
  );
}

/**
 * Props to pass to next/image.
 *
 * - SVGs: always unoptimized — the Next optimizer rejects SVG by default.
 * - Local public files (/media, /uploads, …) that are ALREADY .webp/.avif:
 *   unoptimized — these were generated by the Sharp pipeline and are already
 *   sized/compressed, so re-running them through the runtime optimizer only
 *   adds latency without any quality or byte-size benefit.
 * - Local JPG/JPEG/PNG (not yet processed by the Sharp pipeline): NOT
 *   unoptimized — these must still go through Next's optimizer so mobile
 *   gets a resized/compressed variant instead of the raw original.
 * - Remote Vercel Blob uploads: OPTIMIZED — next.config.ts remotePatterns
 *   allows blob domains, so Next serves resized WebP/AVIF variants instead
 *   of shipping full-size originals to mobile.
 */
export function localImageUnoptimized(src: string): { unoptimized?: true } {
  const isSvg = /\.svg(\?|$)/i.test(src);
  if (isSvg) return { unoptimized: true };

  const isAlreadyOptimizedFormat = /\.(webp|avif)(\?|$)/i.test(src);
  if (isLocalPublicAsset(src) && isAlreadyOptimizedFormat) {
    return { unoptimized: true };
  }

  return {};
}
