/** True for assets served from /public without going through the image optimizer. */
export function isLocalPublicAsset(src: string): boolean {
  return (
    src.startsWith("/media/") ||
    src.startsWith("/uploads/") ||
    src.startsWith("/brand/") ||
    src.startsWith("/api/media/")
  );
}

/** Vercel Blob and other remote CMS uploads. */
export function isRemoteCmsAsset(src: string): boolean {
  return (
    src.includes(".blob.vercel-storage.com/") ||
    src.includes(".public.blob.vercel-storage.com/")
  );
}

/**
 * Props to pass to next/image for general use.
 *
 * - SVGs: always unoptimized — the Next optimizer rejects SVG by default.
 * - Local public files (/media, /uploads, …) that are ALREADY .webp/.avif:
 *   unoptimized — these were generated by the Sharp pipeline and are already
 *   sized/compressed, so re-running them through the runtime optimizer only
 *   adds latency without any quality or byte-size benefit.
 * - Local JPG/JPEG/PNG: NOT unoptimized by default — Next's optimizer resizes
 *   them for the target viewport, which is beneficial for generic thumbnails.
 *   Use localServeDirect() instead when you explicitly need to bypass /_next/image.
 * - Remote Vercel Blob uploads: OPTIMIZED — next.config.ts remotePatterns
 *   allows blob domains, so Next serves resized WebP/AVIF variants instead
 *   of shipping full-size originals to mobile.
 */
export function localImageUnoptimized(src: string): { unoptimized?: true } {
  const isSvg = /\.svg(\?|$)/i.test(src);
  if (isSvg) return { unoptimized: true };

  const isAlreadyOptimizedFormat = /\.(webp|avif)(\?|$)/i.test(src);
  if (isLocalPublicAsset(src) && isAlreadyOptimizedFormat) {
    return { unoptimized: true };
  }

  return {};
}

/**
 * Force direct serving for any local public asset, regardless of extension.
 *
 * Use this when the image is already served from the local filesystem and you
 * want to bypass /_next/image entirely — avoiding the runtime re-encode/resize
 * chain (fetch → Sharp → cache) which adds TTFB latency on uncached requests.
 *
 * Correct for: Hero slides (JPG/WebP from /media/hero-slider/),
 *              Partner logos (JPG/WebP from /media/logo/ or /uploads/logos/).
 *
 * Do NOT use for raw user-uploaded JPG/PNG that still need Next's resize step
 * to deliver a mobile-appropriate size.
 */
export function localServeDirect(src: string): { unoptimized?: true } {
  if (isLocalPublicAsset(src) || /\.svg(\?|$)/i.test(src)) {
    return { unoptimized: true };
  }
  return {};
}
